spring:
  oauth2:
    resource:
      filter-order: 3
  redis:
    host: redissessionoauth2
    port: 6379
    password: redissessionoauth2
    max-total: 128
    max-idle: 128
    min-idle: 16
    min-evictable-idle-time-millis: 60
    time-between-eviction-runs-millis : 30
    block-when-exhausted : true
    use-pool: true
server:
  port: 8080
zuul:
  prefix: /v1
  routes:
    oauth2:
      path: /api/**
      serviceId: oauth2