version: '3'
services: 
  consul:
    container_name: consul
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: |
      sh -c 'set -uex; \
        consul agent -server -bootstrap-expect=1 -data-dir /consul/data -node=agent-one -enable-script-checks=true -ui -disable-host-node-id -client 0.0.0.0 & \
        sleep 20 && \
        consul kv import @/consul/Centralization-Configuration-Consul/apigateway.json && \
        consul kv import @/consul/Centralization-Configuration-Consul/application.json && \
        consul kv import @/consul/Centralization-Configuration-Consul/catalog.json && \
        consul kv import @/consul/Centralization-Configuration-Consul/oauth2.json && \
        consul kv import @/consul/Centralization-Configuration-Consul/transaction.json && \
        tail -f /dev/null'
    volumes: 
      - '/tmp/consul_data_1:/consul/data'
      - './Centralization-Configuration-Consul:/consul/Centralization-Configuration-Consul'
    networks: 
      main:
        aliases: 
          - consul

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks: 
      main:
        aliases: 
          - zipkin

  postgrescatalog:
    container_name: postgrescatalog
    image: postgres:latest
    environment:
      POSTGRES_USER: postgrescatalog
      POSTGRES_PASSWORD: postgrescatalog
      POSTGRES_DB: db_catalog
    networks: 
      main:
        aliases: 
          - postgrescatalog

  catalogservice:
    command: bash -c 'sleep 120 && java -jar /app.jar'
    container_name: catalogservice
    image: org.rizki.mufrizal.catalog.service/catalog-service
    networks: 
      main:
        aliases: 
          - catalogservice

  mongotransaction:
    container_name: mongotransaction
    image: mongo:latest
    networks: 
      main:
        aliases: 
          - mongotransaction

  transactionservice:
    command: bash -c 'sleep 60 && java -jar /app.jar'
    container_name: transactionservice
    image: org.rizki.mufrizal.transaction.service/transaction-service
    networks: 
      main:
        aliases: 
          - transactionservice

  mariadboauth2:
    container_name: mariadboauth2
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mariadboauth2
      MYSQL_USER: mariadboauth2
      MYSQL_PASSWORD: mariadboauth2
      MYSQL_DATABASE: db_oauth2
    networks: 
      main:
        aliases: 
          - mariadboauth2

  redissessionoauth2:
    container_name: redissessionoauth2
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks: 
      main:
        aliases: 
          - redissessionoauth2

  oauth2service:
    command: bash -c 'sleep 60 && java -jar /app.jar'
    container_name: oauth2service
    image: org.rizki.mufrizal.oauth2.service/oauth2-service
    networks: 
      main:
        aliases: 
          - oauth2service

  apigateway:
    command: bash -c 'sleep 60 && java -jar /app.jar'
    container_name: apigateway
    image: org.rizki.mufrizal.api.gateway/api-gateway
    ports: 
      - 8080:8080
    networks: 
      main:
        aliases: 
          - apigateway

  admindashboard:
    command: bash -c 'sleep 20 && java -jar /app.jar'
    container_name: admindashboard
    image: org.rizki.mufrizal.admin.dashboard/admin-dashboard
    ports: 
      - 8181:8181
    networks: 
      main:
        aliases: 
          - admindashboard

networks: 
  main: