version: '3'
services: 
  discovery1:
    command: bash -c 'java -Dspring.profiles.active=discovery1 -jar /app.jar'
    container_name: discovery1
    image: org.rizki.mufrizal.discovery.service/discovery-service
    ports: 
      - 10001:10001
    networks: 
      main:
        aliases: 
          - discovery1

  discovery2:
    command: bash -c 'java -Dspring.profiles.active=discovery2 -jar /app.jar'
    container_name: discovery2
    image: org.rizki.mufrizal.discovery.service/discovery-service
    ports: 
      - 10002:10002
    networks: 
      main:
        aliases: 
          - discovery2

  configurationserver:
    command: bash -c 'java -jar /app.jar'
    container_name: configurationserver
    image: org.rizki.mufrizal.configuration.server/configuration-server
    networks: 
      main:
        aliases: 
          - configurationserver

  postgrescatalog:
    container_name: postgrescatalog
    image: postgres:latest
    environment:
      POSTGRES_USER: postgrescatalog
      POSTGRES_PASSWORD: postgrescatalog
      POSTGRES_DB: db_catalog
    networks: 
      main:
        aliases: 
          - postgrescatalog

  catalogservice:
    command: bash -c 'sleep 120 && java -jar /app.jar'
    container_name: catalogservice
    image: org.rizki.mufrizal.catalog.service/catalog-service
    networks: 
      main:
        aliases: 
          - catalogservice

  mongotransaction:
    container_name: mongotransaction
    image: mongo:latest
    networks: 
      main:
        aliases: 
          - mongotransaction

  transactionservice:
    command: bash -c 'sleep 120 && java -jar /app.jar'
    container_name: transactionservice
    image: org.rizki.mufrizal.transaction.service/transaction-service
    networks: 
      main:
        aliases: 
          - transactionservice

networks: 
  main: