spring:
  oauth2:
    resource:
      filter-order: 3
  redis:
    host: redissessionoauth2
    port: 6379
    password: redissessionoauth2
    max-total: 128
    max-idle: 128
    min-idle: 16
    min-evictable-idle-time-millis: 60
    time-between-eviction-runs-millis : 30
    block-when-exhausted : true
    use-pool: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mariadboauth2:3306/db_oauth2?autoReconnect=true
    username: mariadboauth2
    password: mariadboauth2
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8089
management:
  security:
    enabled: true
security:
  basic:
    enabled: true