spring:
  application:
    name: discovery_service

---
spring:
  profiles: discovery1
  boot:
    admin:
      turbine:
        clusters: default
        location: turbine
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
server:
  port: 10001
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://127.0.0.1:10002/eureka/
    registry-fetch-interval-seconds: 5
  dashboard:
    enabled: false
management:
  security:
    enabled: false

---
spring:
  profiles: discovery2
  boot:
    admin:
      turbine:
        clusters: default
        location: turbine
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
server:
  port: 10002
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/
    registry-fetch-interval-seconds: 5
  dashboard:
    enabled: false
management:
  security:
    enabled: false