spring:
  application:
    name: discovery_service

---
spring:
  profiles: discovery1
server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://discovery2:10002/eureka/

---
spring:
  profiles: discovery2
server:
  port: 10002
eureka:
  client:
    service-url:
      defaultZone: http://discovery1:10001/eureka/