spring:
  application:
    name: discovery_service

---
spring:
  profiles: discovery1
  cloud:
    dashboard:
      http:
        username: actuator
        password: actuator
server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://discovery2:10002/eureka/
    register-with-eureka: true
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
  dashboard:
    enabled: false
management:
  security:
    enabled: false
---
spring:
  profiles: discovery2
  cloud:
    dashboard:
      http:
        username: actuator
        password: actuator
server:
  port: 10002
eureka:
  client:
    service-url:
      defaultZone: http://discovery1:10001/eureka/
    register-with-eureka: true
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
  dashboard:
    enabled: false
management:
  security:
    enabled: false