spring:
  application:
    name: discovery_service

---
spring:
  profiles: discovery1
  boot:
    admin:
      turbine:
        clusters: default
        location: turbine
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
server:
  port: 10001
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://discovery2:10002/eureka/
    registry-fetch-interval-seconds: 5
  dashboard:
    enabled: false
security:
  oauth2:
    client:
      access-token-uri: http://oauth2service:8089/oauth/token
      user-authorization-uri: http://oauth2service:8089/oauth/authorize
      client-id: clientid
      client-secret: secret

---
spring:
  profiles: discovery2
  boot:
    admin:
      turbine:
        clusters: default
        location: turbine
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
server:
  port: 10002
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://discovery1:10001/eureka/
    registry-fetch-interval-seconds: 5
  dashboard:
    enabled: false
security:
  oauth2:
    client:
      access-token-uri: http://oauth2service:8089/oauth/token
      user-authorization-uri: http://oauth2service:8089/oauth/authorize
      client-id: clientid
      client-secret: secret