spring:
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        healthCheckPath: /health-check
        healthCheckInterval: 20s
  data:
    mongodb:
      database: mongotransaction
      host: mongotransaction
      port: 27017
management:
  security:
    enabled: false